# Generated by Django 3.0.7 on 2020-06-16 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200615_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Wordlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=250)),
                ('location', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('tf', models.DecimalField(decimal_places=4, max_digits=5)),
                ('url', models.CharField(default='', max_length=250)),
                ('d', models.IntegerField(default=0)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.News')),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Word')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
