# Generated by Django 3.0.7 on 2020-06-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0004_likes_my_lenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_lenta',
            name='interfax',
            field=models.BooleanField(default=False, verbose_name='Interfax'),
        ),
        migrations.AlterField(
            model_name='my_lenta',
            name='lenta_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='my_lenta',
            name='regnum',
            field=models.BooleanField(default=False, verbose_name='REGNUM'),
        ),
        migrations.AlterField(
            model_name='my_lenta',
            name='ria',
            field=models.BooleanField(default=False, verbose_name='РИА новости'),
        ),
        migrations.AlterField(
            model_name='my_lenta',
            name='rt',
            field=models.BooleanField(default=False, verbose_name='RT'),
        ),
    ]
