# Generated by Django 3.0.7 on 2020-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200616_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_lenta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
