# Generated by Django 3.0.7 on 2020-06-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraping', '0007_auto_20200616_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_lenta',
            name='id',
        ),
        migrations.AlterField(
            model_name='my_lenta',
            name='lenta_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
